# Generated by Django 4.2.5 on 2023-10-31 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='description_programme',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionga.domaine')),
                ('droit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionga.droit')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionga.profil')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionga.programme')),
            ],
        ),
    ]
