# Generated by Django 4.2.5 on 2023-11-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0003_alter_habilitation_domaine_alter_habilitation_droit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
