# Generated by Django 4.2.5 on 2023-11-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0004_utilisateurs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateurs',
            new_name='Utilisateur',
        ),
    ]
