# Generated by Django 4.2.5 on 2023-11-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0005_rename_utilisateurs_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('departement', models.CharField(choices=[('GA1', 'GA 1'), ('GA2', 'GA 2')], max_length=10)),
                ('service', models.CharField(choices=[('GDD', 'GDD'), ('REFERENTIEL', 'REFERENTIEL'), ('ENGAGEMENT', 'ENGAGEMENT'), ('CANAUX_ET_CONFORMITE', 'CANAUX ET CONFORMITE'), ('MONETIQUE', 'MONETIQUE'), ('CASH_MANAGEMENT', 'CASH MANAGEMENT')], max_length=50)),
                ('statut', models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe'), ('Stagiaire', 'Stagiaire')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
