# Generated by Django 4.2.5 on 2023-11-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0006_ressource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='numero_ip',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
