# Generated by Django 4.2.5 on 2023-11-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0007_alter_ressource_numero_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
