# Generated by Django 4.2.5 on 2023-11-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0008_delete_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='numero_ip',
        ),
        migrations.AddField(
            model_name='ressource',
            name='poste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
