# Generated by Django 4.2.5 on 2023-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0010_remove_ressource_poste_ressource_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
