# Generated by Django 4.2.5 on 2023-11-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0011_alter_ressource_email_alter_ressource_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=70)),
            ],
        ),
    ]
