# Generated by Django 4.2.5 on 2023-12-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0014_alter_application_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('typ', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sgbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sgbf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sgcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sgci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sgcongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sgm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sgsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sgtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_module', models.CharField(max_length=70)),
                ('description_module', models.CharField(max_length=100)),
            ],
        ),
    ]
