# Generated by Django 4.2.5 on 2023-12-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0017_alter_ressourceapplication_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourceOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=20)),
                ('numero_ip', models.GenericIPAddressField()),
                ('departement', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_desactivation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
