# Generated by Django 4.2.6 on 2024-01-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0018_ressourceoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.TextField()),
                ('programme_filiale', models.TextField()),
                ('intitule', models.TextField()),
                ('cmis', models.TextField()),
            ],
        ),
    ]
