# Generated by Django 4.2.6 on 2024-01-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0019_resultatrecherche'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='manager',
            field=models.CharField(choices=[('KOFFI KATCHE OLIVIER', 'KOFFI KATCHE OLIVIER'), ('DOUANLA FLEURETTE', 'DOUANLA FLEURETTE')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
