# Generated by Django 4.2.6 on 2024-01-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0020_ressource_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourceoff',
            name='manager',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
