# Generated by Django 4.2.6 on 2024-01-16 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0021_ressourceoff_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='ressourceoff',
            name='manager',
        ),
    ]
