# Generated by Django 4.2.6 on 2024-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0022_remove_ressource_manager_remove_ressourceoff_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='manager',
            field=models.CharField(choices=[('KOFFI KATCHE OLIVIER', 'KOFFI KATCHE OLIVIER'), ('DOUANLA FLEURETTE', 'DOUANLA FLEURETTE')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ressourceoff',
            name='manager',
            field=models.CharField(choices=[('KOFFI KATCHE OLIVIER', 'KOFFI KATCHE OLIVIER'), ('DOUANLA FLEURETTE', 'DOUANLA FLEURETTE')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
