# Generated by Django 4.2.6 on 2024-01-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0023_ressource_manager_ressourceoff_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressourceoff',
            name='numero_ip',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
