# Generated by Django 4.2.6 on 2024-02-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionga', '0024_alter_ressourceoff_numero_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgbeX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SgbfX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SgcamX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SgciX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SgcongoX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SgsnX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SgtgX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('programme_filiale', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('cmis', models.CharField(max_length=100)),
            ],
        ),
    ]
